// const SERVER_BASE_URL = "http://localhost:5000/";
const SERVER_BASE_URL = "https://api-service-finder.herokuapp.com/";
const CLIENT_BASE_URL = "http://localhost:3000/";
const GOOGLE_MAP_API_KEY = "AIzaSyCLwLUlZEALsUUhJ0bOmuu_ciYvWnuhsCc";

// const PRE_ROUTE = "/";
const PRE_ROUTE = "/service_finder_client/";

const NO_PARAM_ROUTES = {
  VERIFY_EMAIL: `${PRE_ROUTE}verify`,
  PERSONAL_DETAIL: `${PRE_ROUTE}personal-detail`,
  SEARCH_SERVICES: `${PRE_ROUTE}search-services`,
  CATEGORY: `${PRE_ROUTE}category`,
  SERVICE_DETAIL: `${PRE_ROUTE}service`,
  SELLER: `${PRE_ROUTE}seller`,
};

const ROUTE_NAMES = {
  HOME: PRE_ROUTE,
  SIGNUP: `${PRE_ROUTE}signup`,
  LOGIN: `${PRE_ROUTE}login`,
  VERIFY_EMAIL: NO_PARAM_ROUTES.VERIFY_EMAIL,
  VERIFY_EMAIL_PARAMS: `${NO_PARAM_ROUTES.VERIFY_EMAIL}/:email`,
  PERSONAL_DETAIL: NO_PARAM_ROUTES.PERSONAL_DETAIL,
  PERSONAL_DETAIL_PARAMS: `${NO_PARAM_ROUTES.PERSONAL_DETAIL}/:email`,
  SEARCH_SERVICES: NO_PARAM_ROUTES.SEARCH_SERVICES,
  SEARCH_SERVICES_PARAMS: `${NO_PARAM_ROUTES.SEARCH_SERVICES}/:keyword/:category_id/:latitude/:longitude`,
  CATEGORY: NO_PARAM_ROUTES.CATEGORY,
  CATEGORY_PARAMS: `${NO_PARAM_ROUTES.CATEGORY}/:category_id`,
  SERVICES: `${PRE_ROUTE}services`,
  SERVICE_DETAIL: NO_PARAM_ROUTES.SERVICE_DETAIL,
  SERVICE_DETAIL_PARAMS: `${NO_PARAM_ROUTES.SERVICE_DETAIL}/:service_id`,
  SELLER: NO_PARAM_ROUTES.SELLER,
  SELLER_PARAMS: `${NO_PARAM_ROUTES.SELLER}/:seller_user_id`,
  CONTACT_US: `${PRE_ROUTE}contact-us`,
  ABOUT_US: `${PRE_ROUTE}about-us`,
  ADD_CATEGORY: `${PRE_ROUTE}add-category`,
  ADD_HERO_SLIDER: `${PRE_ROUTE}add-hero-slider`,
};

export { SERVER_BASE_URL, CLIENT_BASE_URL, GOOGLE_MAP_API_KEY, ROUTE_NAMES };
